---

- name: eth0 config
  template:
    src: eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0

- name: eth1 config
  template:
    src: eth1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1

- name: bond0 config
  template:
    src: bond0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-bond0

- name: bonding mod
  copy:
    src: bonding.conf
    dest: /etc/modprobe.d/bonding.conf
