---

- name: copy flanneld
  copy:
    src: flanneld
    dest: /export/servers
    mode: 755
  tags: flanneld

- name: copy flanneld systemd config
  template:
    src: flanneld.service.j2
    dest: /etc/systemd/system/flanneld.service
  tags: 
    - flanneld

- name: reload systemd
  shell: systemctl daemon-reload
  tags:
    - flanneld

- name: start flanneld
  service:
    name: flanneld
    state: restarted
  tags: flanneld

 
