---

- name: copy kubelet systemd config
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
  tags:
    - kube-proxy

- name: reload systemd
  shell: systemctl daemon-reload
  tags:
    - kube-proxy

- name: start kube-proxy
  service:
    name: kube-proxy
    state: restarted
  tags: kube-proxy
 
