---

- name: mkfs parted  ext4
  filesystem: 
    fstype: ext4
    dev: '/dev/{{ item.disk }}'
  with_items:
    - { "disk": "nvme1n1p1"}
    - { "disk": "nvme1n1p2"}
    - { "disk": "nvme1n1p3"}
    - { "disk": "nvme2n1p1"}
    - { "disk": "nvme2n1p2"}
    - { "disk": "nvme2n1p3"}
    - { "disk": "nvme3n1p1"}
    - { "disk": "nvme3n1p2"}
    - { "disk": "nvme3n1p3"}

