---

- name: start kafka1
  become: true
  become_method: su
  shell: source /export/App/kafka_2.11-0.10.1.1/bin/kafka-env.sh;/export/App/kafka_2.11-0.10.1.1/bin/kafka-server-start.sh  -daemon /export/App/kafka_2.11-0.10.1.1/config/server.properties
  become_user: hadoop
  tags: start_kafka1

- name: start kafka2
  become: true
  become_method: su
  shell: source /export/App/kafka_2.10-0.8.2.1/bin/kafka-env.sh;/export/App/kafka_2.10-0.8.2.1/bin/kafka-server-start.sh  -daemon /export/App/kafka_2.10-0.8.2.1/config/server.properties
  become_user: hadoop
  tags: start_kafka2

 
- name: start kafka3
  become: true
  become_method: su
  shell: source /export/App/kafka_2.11-1.0.0/bin/kafka-env.sh;/export/App/kafka_2.11-1.0.0/bin/kafka-server-start.sh  -daemon /export/App/kafka_2.11-1.0.0/config/server.properties
  become_user: hadoop
  tags: start_kafka3
